import {Component, Input, OnInit} from '@angular/core';
import {Router} from '@angular/router';

@Component({
  selector: 'app-personal-entity-list',
  templateUrl: './personal-entity-list.component.html',
  styleUrls: ['./personal-entity-list.component.scss']
})
export class PersonalEntityListComponent implements OnInit {

  detailsFlag = false;
  person;

  fsList: {

    customerName: string,
    customerType: string,
    relationshipType: string,
    nationalCode: string,
    registrationDate: number,
    organizationalRole: string,
    personalCode: number,
    banck: string,
    firstName: string,
    lastName: string,
    fatherName: string,
    numberShenasname: number,
    dateShenasname: number,
    seriShenasname: string,
    addadShenasname: number,
    seryalShenasname: number,
    seryalkartMeli: string,
    shenasnameType: string,
    city: string,
    country: string,
    religion: string,
    sect: string,
    residence: string,
    enDate: number,
    enName: string,
    enFatherName: string,
    erjaCode: string,
    eduMaghta: string,
    eduReshte: string,
    eduGraesh: string,
    eduMoaseseType: string,
    eduMoaseseName: string,
    startDate: number,
    endDate: number,
    recruitmentType: string,
    post: string,
    vahed: string,
    sahmie: string,
    tedadFamily: number,
    tedadChild: number,
    tedadKefalat: number,
    contactNumber:string,
    enLastName:string,
    codeHoze:string,
    genderType:string,
    birthDate:number

  }[] = [
    {
      'customerName': 'پژمان سهرابی',
      'registrationDate': 14000610,
      'contactNumber': '09006489207',
      'customerType': 'حقیقی',
      'relationshipType': 'کارمند',
      'nationalCode': '2235425126',
      'organizationalRole': 'مدیر ارشد فناوری',
      'personalCode': 12400,
      'banck': '1',
      'firstName': 'پژمان',
      'lastName': 'سهرابی',
      'fatherName': 'فریدون',
      'numberShenasname': 2235425126,
      'dateShenasname': 13740503,
      'birthDate': 13740501,
      'seriShenasname': 'د',
      'addadShenasname': 19,
      'seryalShenasname': 625231,
      'seryalkartMeli':  '2540502361',
      'shenasnameType': '1',
      'codeHoze':'2',
      'city': '4',
      'country': '1',
      'religion': '1',
      'sect': '1',
      'residence': '1',
      'enDate': 25072003,
      'enName': 'pejman',
      'enLastName': 'sohrabi',
      'enFatherName': 'freydon',
      'erjaCode': '32131',
      'eduMaghta': 'کارشناسی ارشد',
      'eduReshte': 'کامپیوتر',
      'eduGraesh': 'سخت افزار',
      'eduMoaseseType': 'دولتی',
      'eduMoaseseName': 'دانشگاه تهران',
      'startDate': 13940701,
      'endDate': 13981001,
      'recruitmentType': 'دائم',
      'post': 'معمار سیستم',
      'vahed': 'فناوری',
      'sahmie': 'ندارد',
      'tedadFamily': 4,
      'tedadChild': 2,
      'tedadKefalat': 1,
      'genderType':'1'
    },
    {
      'customerName': 'کامران گیلانی',
      'registrationDate': 14000721,
      'contactNumber': '09016485057',
      'customerType': 'حقیقی',
      'relationshipType': 'کارمند',
      'nationalCode': '4598442678',
      'organizationalRole': 'مدیر عامل',
      'personalCode': 11000,
      'banck': '2',
      'firstName': 'کامران',
      'lastName': 'گیلانی',
      'fatherName': 'سینا',
      'numberShenasname': 4598442678,
      'dateShenasname': 13620503,
      'birthDate': 13620501,
      'seriShenasname': 'ب',
      'addadShenasname': 15,
      'seryalShenasname': 658245,
      'seryalkartMeli':  '1250002563',
      'shenasnameType': '1',
      'city': '4',
      'country': '1',
      'religion': '1',
      'sect': '1',
      'residence': '1',
      'enDate': 25071995,
      'enName': 'kamran',
      'enLastName': 'gilani',
      'enFatherName': 'sina',
      'erjaCode': '25468',
      'eduMaghta': 'دکتری',
      'eduReshte': 'مدیریت',
      'eduGraesh': 'کار آفرینی',
      'eduMoaseseType': 'دولتی',
      'eduMoaseseName': 'شهید بهشتی',
      'startDate': 13740701,
      'endDate': 13781001,
      'recruitmentType': 'دائم',
      'post': 'مدیر عامل',
      'vahed': 'مدیریت',
      'sahmie': 'ندارد',
      'tedadFamily': 5,
      'tedadChild': 3,
      'tedadKefalat': 0,
      'codeHoze':'1',
      'genderType':'1'
    },
    {
      'customerName': 'کارگزاری بیمه سامان',
      'registrationDate': 14000910,
      'contactNumber': '09016485057',
      'customerType': 'حقوقی',
      'relationshipType': 'نمایندگی بیمه',
      'nationalCode': '',
      'organizationalRole': '',
      'personalCode': null,
      'banck': '4',
      'firstName': '',
      'lastName': '',
      'fatherName': '',
      'numberShenasname': null,
      'dateShenasname': null,
      'seriShenasname': '',
      'addadShenasname': null,
      'seryalShenasname': null,
      'seryalkartMeli':  '',
      'shenasnameType': '',
      'city': '4',
      'country': '1',
      'religion': '',
      'sect': '',
      'residence': '',
      'enDate': null,
      'enName': '',
      'enLastName': '',
      'enFatherName': '',
      'erjaCode': '36214',
      'eduMaghta': '',
      'eduReshte': '',
      'eduGraesh': '',
      'eduMoaseseType': '',
      'eduMoaseseName': '',
      'startDate': null,
      'endDate': null,
      'recruitmentType': '',
      'post': '',
      'vahed': '',
      'sahmie': '',
      'tedadFamily': null,
      'tedadChild': null,
      'tedadKefalat': null,
      'codeHoze':'',
      'genderType':'',
      'birthDate': null,
    },
    {
      customerName: 'تامین کننده مواد اولیه',
      registrationDate: 14000910,
      contactNumber: '021-88584420',
      customerType: 'حقوقی',
      relationshipType: 'تامین کننده',
      'nationalCode': '',
      'organizationalRole': '',
      'personalCode': null,
      'banck': '4',
      'firstName': '',
      'lastName': '',
      'fatherName': '',
      'numberShenasname': null,
      'dateShenasname': null,
      'seriShenasname': '',
      'addadShenasname': null,
      'seryalShenasname': null,
      'seryalkartMeli':  '',
      'shenasnameType': '',
      'city': '4',
      'country': '1',
      'religion': '',
      'sect': '',
      'residence': '',
      'enDate': null,
      'enName': '',
      'enLastName': '',
      'enFatherName': '',
      'erjaCode': '36214',
      'eduMaghta': '',
      'eduReshte': '',
      'eduGraesh': '',
      'eduMoaseseType': '',
      'eduMoaseseName': '',
      'startDate': null,
      'endDate': null,
      'recruitmentType': '',
      'post': '',
      'vahed': '',
      'sahmie': '',
      'tedadFamily': null,
      'tedadChild': null,
      'tedadKefalat': null,
      'codeHoze':'',
      'genderType':'',
      'birthDate': null,
    },
  ];
  selectedRow: Row;

  constructor(private router: Router) {
  }

  ngOnInit(): void {
  }
  onClose(event: any){
    if (event==='close')
      this.detailsFlag = false;
  }
  selectRow(servise): void {
    debugger
    this.person = {
      customerName: '',
      customerType: '',
      nationalCode: '',
      registrationDate: 0,
      organizationalRole: '',
      personalCode: 0,
      banck: '',
      firstName: '',
      lastName: '',
      fatherName: '',
      numberShenasname: 0,
      dateShenasname: 0,
      seriShenasname: '',
      addadShenasname: '',
      seryalShenasname: '',
      seryalkartMeli: '',
      shenasnameType: '',
      city: '',
      country: '',
      religion: '',
      sect: '',
      residence: '',
      enDate: '',
      enName: '',
      enFatherName: '',
      erjaCode: '',
      eduMaghta: '',
      eduReshte: '',
      eduGraesh: '',
      eduMoaseseType: '',
      eduMoaseseName: '',
      startDate: 0,
      endDate: 0,
      recruitmentType: '',
      post: '',
      vahed: '',
      sahmie: '',
      tedadFamily: 0,
      tedadChild: 0,
      tedadKefalat: 0,
      contactNumber:'',
      fieldOfActivity:'',
      relationshipType:''

    };
    this.fsList = servise;
    debugger
    this.detailsFlag = true;
  }
}

interface Row {
  fullName
  registrationDate
  contactNumber
  fieldOfActivity
  relationshipType
}
