import {Component, OnInit} from '@angular/core';
import {Router} from '@angular/router';

@Component({
  selector: 'app-personal-entity-list',
  templateUrl: './personal-entity-list.component.html',
  styleUrls: ['./personal-entity-list.component.scss']
})
export class PersonalEntityListComponent implements OnInit {
  detailsFlag = false;
  person;
  rows: Row[] = [
    {
      fullName: 'پژمان سهرابی',
      registrationDate: 14000610,
      contactNumber: '09006489207',
      fieldOfActivity: 'حقیقی',
      relationshipType: 'کارمند',
    },
    {
      fullName: 'کامران گیلانی',
      registrationDate: 14000721,
      contactNumber: '09016485057',
      fieldOfActivity: 'حقیقی',
      relationshipType: 'کارمند',
    },
    // {
    //   fullName: 'هوشنگ مقتصد',
    //   registrationDate: 14000819,
    //   contactNumber: '09338854727',
    //   fieldOfActivity: 'حقیقی',
    //   relationshipType: 'کارمند',
    // },
    {
      fullName: 'کارگزاری بیمه سامان',
      registrationDate: 14000910,
      contactNumber: '09016485057',
      fieldOfActivity: 'حقوقی',
      relationshipType: 'نمایندگی بیمه',
    },
    {
      fullName: 'تامین کننده مواد اولیه',
      registrationDate: 14000910,
      contactNumber: '021-88584420',
      fieldOfActivity: 'حقوقی',
      relationshipType: 'تامین کننده',
    },
  ];
  fsList: {
    customerName: string,
    customerType: string,
    relationshipType: string,
    nationalCode: string,
    registrationDate: number,
    organizationalRole: string,
    personalCode: number,
    banck: string,
    firstName: string,
    lastName: string,
    fatherName: string,
    NumberShenasname: number,
    DateShenasname: number,
    seriShenasname: string,
    addadShenasname: number,
    seryalShenasname: number,
    seryalkartMeli: string,
    shenasnameType: string,
    city: string,
    country: string,
    religion: string,
    sect: string,
    residence: string,
    EnDate: number,
    EnName: string,
    EnFatherName: string,
    erjaCode: string,
    eduMaghta: string,
    eduReshte: string,
    eduGraesh: string,
    eduMoaseseType: string,
    eduMoaseseName: string,
    startDate: number,
    endDate: number,
    recruitmentType: string,
    post: string,
    vahed: string,
    sahmie: string,
    tedadFamily: number,
    tedadChild: number,
    tedadKefalat: number,
    contactNumber:string,
    EnLastName:string

  }[] = [
    {
      'customerName': 'پژمان سهرابی',
      'registrationDate': 14000610,
      'contactNumber': '09006489207',
      'customerType': 'حقیقی',
      'relationshipType': 'کارمند',
      'nationalCode': '2235425126',
      'organizationalRole': 'مدیر ارشد فناوری',
      'personalCode': 12400,
      'banck': '1',
      'firstName': 'پژمان',
      'lastName': 'سهرابی',
      'fatherName': 'فریدون',
      'NumberShenasname': 2124584185,
      'DateShenasname': 13740503,
      'seriShenasname': 'د',
      'addadShenasname': 19,
      'seryalShenasname': 625231,
      'seryalkartMeli':  '2540502361',
      'shenasnameType': 'المثنی',
      'city': '4',
      'country': '1',
      'religion': '1',
      'sect': '1',
      'residence': '1',
      'EnDate': 20030725,
      'EnName': 'pejman',
      'EnLastName': 'sohrabi',
      'EnFatherName': 'freydon',
      'erjaCode': '32131',
      'eduMaghta': 'کارشناسی ارشد',
      'eduReshte': 'کامپیوتر',
      'eduGraesh': 'سخت افزار',
      'eduMoaseseType': 'دولتی',
      'eduMoaseseName': 'دانشگاه تهران',
      'startDate': 13940701,
      'endDate': 13981001,
      'recruitmentType': 'دائم',
      'post': 'معمار سیستم',
      'vahed': 'فناوری',
      'sahmie': 'ندارد',
      'tedadFamily': 4,
      'tedadChild': 2,
      'tedadKefalat': 1,
    },
    {
      'customerName': 'کامران گیلانی',
      'registrationDate': 14000721,
      'contactNumber': '09016485057',
      'customerType': 'حقیقی',
      'relationshipType': 'کارمند',
      'nationalCode': '4598442678',
      'organizationalRole': 'مدیر عامل',
      'personalCode': 11000,
      'banck': '2',
      'firstName': 'کامران',
      'lastName': 'گیلانی',
      'fatherName': 'سینا',
      'NumberShenasname': 2566525181,
      'DateShenasname': 13620503,
      'seriShenasname': 'ب',
      'addadShenasname': 15,
      'seryalShenasname': 658245,
      'seryalkartMeli':  '1250002563',
      'shenasnameType': 'المثنی',
      'city': '4',
      'country': '1',
      'religion': '1',
      'sect': '1',
      'residence': '1',
      'EnDate': 19950725,
      'EnName': 'kamran',
      'EnLastName': 'gilani',
      'EnFatherName': 'sina',
      'erjaCode': '25468',
      'eduMaghta': 'دکتری',
      'eduReshte': 'مدیریت',
      'eduGraesh': 'کار آفرینی',
      'eduMoaseseType': 'دولتی',
      'eduMoaseseName': 'شهید بهشتی',
      'startDate': 13740701,
      'endDate': 13781001,
      'recruitmentType': 'دائم',
      'post': 'مدیر عامل',
      'vahed': 'مدیریت',
      'sahmie': 'ندارد',
      'tedadFamily': 5,
      'tedadChild': 3,
      'tedadKefalat': 0,
    },
    {
      'customerName': 'کارگزاری بیمه سامان',
      'registrationDate': 14000910,
      'contactNumber': '09016485057',
      'customerType': 'حقوقی',
      'relationshipType': 'نمایندگی بیمه',
      'nationalCode': '',
      'organizationalRole': '',
      'personalCode': null,
      'banck': '4',
      'firstName': '',
      'lastName': '',
      'fatherName': '',
      'NumberShenasname': null,
      'DateShenasname': null,
      'seriShenasname': '',
      'addadShenasname': null,
      'seryalShenasname': null,
      'seryalkartMeli':  '',
      'shenasnameType': '',
      'city': '4',
      'country': '1',
      'religion': '',
      'sect': '',
      'residence': '',
      'EnDate': null,
      'EnName': '',
      'EnLastName': '',
      'EnFatherName': '',
      'erjaCode': '36214',
      'eduMaghta': '',
      'eduReshte': '',
      'eduGraesh': '',
      'eduMoaseseType': '',
      'eduMoaseseName': '',
      'startDate': null,
      'endDate': null,
      'recruitmentType': '',
      'post': '',
      'vahed': '',
      'sahmie': '',
      'tedadFamily': null,
      'tedadChild': null,
      'tedadKefalat': null,
    },
    {
      customerName: 'تامین کننده مواد اولیه',
      registrationDate: 14000910,
      contactNumber: '021-88584420',
      customerType: 'حقوقی',
      relationshipType: 'تامین کننده',
      'nationalCode': '',
      'organizationalRole': '',
      'personalCode': null,
      'banck': '4',
      'firstName': '',
      'lastName': '',
      'fatherName': '',
      'NumberShenasname': null,
      'DateShenasname': null,
      'seriShenasname': '',
      'addadShenasname': null,
      'seryalShenasname': null,
      'seryalkartMeli':  '',
      'shenasnameType': '',
      'city': '4',
      'country': '1',
      'religion': '',
      'sect': '',
      'residence': '',
      'EnDate': null,
      'EnName': '',
      'EnLastName': '',
      'EnFatherName': '',
      'erjaCode': '36214',
      'eduMaghta': '',
      'eduReshte': '',
      'eduGraesh': '',
      'eduMoaseseType': '',
      'eduMoaseseName': '',
      'startDate': null,
      'endDate': null,
      'recruitmentType': '',
      'post': '',
      'vahed': '',
      'sahmie': '',
      'tedadFamily': null,
      'tedadChild': null,
      'tedadKefalat': null,
    },
  ];
  selectedRow: Row;

  constructor(private router: Router) {
  }

  ngOnInit(): void {
  }

  selectRow(servise): void {
    this.person = {
      customerName: '',
      customerType: '',
      nationalCode: '',
      registrationDate: 0,
      organizationalRole: '',
      personalCode: 0,
      banck: '',
      firstName: '',
      lastName: '',
      fatherName: '',
      NumberShenasname: 0,
      DateShenasname: 0,
      seriShenasname: '',
      addadShenasname: '',
      seryalShenasname: '',
      seryalkartMeli: '',
      shenasnameType: '',
      city: '',
      country: '',
      religion: '',
      sect: '',
      residence: '',
      EnDate: '',
      EnName: '',
      EnFatherName: '',
      erjaCode: '',
      eduMaghta: '',
      eduReshte: '',
      eduGraesh: '',
      eduMoaseseType: '',
      eduMoaseseName: '',
      startDate: 0,
      endDate: 0,
      recruitmentType: '',
      post: '',
      vahed: '',
      sahmie: '',
      tedadFamily: 0,
      tedadChild: 0,
      tedadKefalat: 0,
      contactNumber:'',
      fieldOfActivity:'',
      relationshipType:''

    };
    this.fsList = servise;
    debugger
    this.detailsFlag = true;
  }
}

interface Row {
  fullName
  registrationDate
  contactNumber
  fieldOfActivity
  relationshipType
}
