import {Component, OnInit} from '@angular/core';
import {Router} from '@angular/router';

@Component({
  selector: 'app-organizational-entity-list',
  templateUrl: './organizational-entity-list.component.html',
  styleUrls: ['./organizational-entity-list.component.scss']
})
export class OrganizationalEntityListComponent implements OnInit {

  detailsFlag = false;
  viewMode = false;
  person;

  fsList: {
    customerName: string,
    customerType: string,
    relationshipType: string,
    nationalCode: string,
    registrationDate: number,
    organizationalRole: string,
    personalCode: number,
    bank: string,
    firstName: string,
    lastName: string,
    fatherName: string,
    numberShenasname: number,
    dateShenasname: number,
    seriShenasname: string,
    addadShenasname: number,
    seryalShenasname: number,
    seryalkartMeli: string,
    shenasnameType: string,
    city: string,
    country: string,
    religion: string,
    sect: string,
    residence: string,
    enDate: string,
    enName: string,
    enFatherName: string,
    erjaCode: string,
    eduMaghta: string,
    eduReshte: string,
    eduGraesh: string,
    eduMoaseseType: string,
    eduMoaseseName: string,
    startDate: number,
    endDate: number,
    recruitmentType: string,
    post: string,
    vahed: string,
    sahmie: string,
    tedadFamily: number,
    tedadChild: number,
    tedadKefalat: number,
    contactNumber: string,
    enLastName: string,
    codeHoze: string,
    genderType: string,
    birthDate: number,
    contactsType: string,
    phoneNumber: string,
    contactTypeGroups: string,
    contactStartDate: string,
    contactEndDate: string,
    contactProvince: string,
    contactCity: string,
    nahveTasarofs: string,
    addressDescription: string,
    postalCode: string,
    contactsStartDate: string
    contactsEndDate: string
    region: string,
    eduCity: string,
    mantaghe: string,
    contactTypes: string,
    zinafType: string,
    statusZinaf: string,
    shahabCode: string,
    noMalekiat: string,
    title: string,
    enTitle: string,
    numberSubmit: string,
    numberNewspaperOfficial: string,
    areaRegistration: string,
    dateRegistration: string,

  }[] = [
    {
      'customerName': 'کارگزاری بیمه سامان',
      'registrationDate': 14000910,
      'contactNumber': '09016485057',
      'customerType': 'حقوقی',
      'relationshipType': 'نمایندگی بیمه',
      'nationalCode': '0020563255',
      'organizationalRole': '2',
      'personalCode': 33113,
      'bank': '4',
      'zinafType': '1',
      'statusZinaf': '2',
      'shahabCode': '1546345658855253',
      'noMalekiat': '1',
      'title': ' ',
      'enTitle': ' ',
      'numberSubmit': ' ',
      'numberNewspaperOfficial': ' ',
      'areaRegistration': ' ',
      'dateRegistration': '1400/05/06',
      'firstName': '',
      'lastName': '',
      'fatherName': '',
      'numberShenasname': null,
      'dateShenasname': null,
      'seriShenasname': '',
      'addadShenasname': null,
      'seryalShenasname': null,
      'seryalkartMeli': '',
      'shenasnameType': '',
      'city': '4',
      'country': '1',
      'religion': '',
      'sect': '',
      'residence': '',
      'enDate': null,
      'enName': '',
      'enLastName': '',
      'enFatherName': '',
      'erjaCode': '36214',
      'eduMaghta': '',
      'eduReshte': '',
      'eduGraesh': '',
      'eduMoaseseType': '',
      'eduMoaseseName': '',
      'startDate': null,
      'endDate': null,
      'eduCity': '',
      'recruitmentType': '',
      'post': '',
      'vahed': '',
      'sahmie': '',
      'tedadFamily': null,
      'tedadChild': null,
      'tedadKefalat': null,
      'codeHoze': '',
      'genderType': '',
      'birthDate': null,
      'contactsType': '1',
      'phoneNumber': '02188452894',
      'contactTypeGroups': '2',
      'contactStartDate': '1400/05/06',
      'contactEndDate': '1400/06/06',
      'contactProvince': '',
      'contactCity': '',
      'nahveTasarofs': '',
      'addressDescription': '',
      'postalCode': '',
      'contactsStartDate': '',
      'contactsEndDate': '',
      'region': '',
      'mantaghe': '',
      'contactTypes': ''
    },
    {
      customerName: 'تامین کننده مواد اولیه',
      registrationDate: 14000910,
      contactNumber: '021-88584420',
      customerType: 'حقوقی',
      relationshipType: 'تامین کننده',
      'nationalCode': '',
      'organizationalRole': '',
      'personalCode': null,
      'bank': '4',
      'zinafType': '2',
      'statusZinaf': '1',
      'shahabCode': '5641354544868445',
      'noMalekiat': '1',
      'title': ' ',
      'enTitle': ' ',
      'numberSubmit': ' ',
      'numberNewspaperOfficial': ' ',
      'areaRegistration': ' ',
      'dateRegistration': '1400/02/04',
      'firstName': '',
      'lastName': '',
      'fatherName': '',
      'numberShenasname': null,
      'dateShenasname': null,
      'seriShenasname': '',
      'addadShenasname': null,
      'seryalShenasname': null,
      'seryalkartMeli': '',
      'shenasnameType': '',
      'city': '4',
      'country': '1',
      'religion': '',
      'sect': '',
      'residence': '',
      'enDate': null,
      'enName': '',
      'enLastName': '',
      'enFatherName': '',
      'erjaCode': '36214',
      'eduMaghta': '',
      'eduReshte': '',
      'eduGraesh': '',
      'eduMoaseseType': '',
      'eduMoaseseName': '',
      'startDate': null,
      'endDate': null,
      'eduCity': '',
      'recruitmentType': '',
      'post': '',
      'vahed': '',
      'sahmie': '',
      'tedadFamily': null,
      'tedadChild': null,
      'tedadKefalat': null,
      'codeHoze': '',
      'genderType': '',
      'birthDate': null,
      'contactsType': '1',
      'phoneNumber': '02177254896',
      'contactTypeGroups': '3',
      'contactStartDate': '1400/06/01',
      'contactEndDate': '1400/07/01',
      'contactProvince': '',
      'contactCity': '',
      'nahveTasarofs': '',
      'addressDescription': '',
      'postalCode': '',
      'contactsStartDate': '',
      'contactsEndDate': '',
      'region': '',
      'mantaghe': '',
      'contactTypes': ' '
    },
  ];
  selectedRow: Row;

  constructor(private router: Router) {
  }

  ngOnInit(): void {
  }

  onClose(event: any) {
    if (event === 'close') {
      this.detailsFlag = false;
      this.viewMode = false;
    }
  }

  selectRow(servise, mode: 'edit' | 'view' = 'edit'): void {
    this.fsList = servise;
    this.viewMode = mode === 'view';
    this.detailsFlag = true;
  }
}

interface Row {
  fullName
  registrationDate
  contactNumber
  fieldOfActivity
  relationshipType
}
